oft_add_exe( test_tokmug.F90 )
install(FILES oft.in DESTINATION examples/MUG/tok_mug COMPONENT examples)
configure_file( oft.in ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES equilibrium.h5 DESTINATION examples/MUG/tok_mug COMPONENT examples)
configure_file( equilibrium.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES eq_o3.h5 DESTINATION examples/MUG/tok_mug COMPONENT examples)
configure_file( eq_o3.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES paper_pert_0115.h5 DESTINATION examples/MUG/tok_mug COMPONENT examples)
configure_file( paper_pert_0115.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES tokamaker_f.prof DESTINATION examples/MUG/tok_mug COMPONENT examples)
configure_file( tokamaker_f.prof ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES tokamaker_p.prof DESTINATION examples/MUG/tok_mug COMPONENT examples)
configure_file( tokamaker_p.prof ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)