oft_add_exe( em_pump.F90 )
install(FILES oft.in DESTINATION examples/MUG/em_pump COMPONENT examples)
configure_file( oft.in ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES pump_mesh_native.h5 DESTINATION examples/MUG/em_pump COMPONENT examples)
configure_file( pump_mesh_native.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES make_pump_mesh.py DESTINATION examples/MUG/em_pump COMPONENT examples)
configure_file( make_pump_mesh.py ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES pump_force.py DESTINATION examples/MUG/em_pump COMPONENT examples)
configure_file( pump_force.py ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
